# Usa la imagen oficial de Node.js
FROM node:14
# Establece el directorio de trabajo
WORKDIR /app
# Copia los archivos necesarios
COPY package.json /app
COPY app.js /app
# Instala dependencias
RUN npm install
# Expone el puerto
EXPOSE 3000
# Comando para iniciar la aplicación
CMD ["node", "app.js"]
