# Usa la imagen oficial de MySQL
FROM mysql:latest
# Establece variables de entorno
ENV MYSQL_ROOT_PASSWORD=mysecretpassword
ENV MYSQL_DATABASE=demo
ENV MYSQL_USER=dennys
ENV MYSQL_PASSWORD=demo
# Copia la configuración personalizada de MySQL
#COPY my.cnf /etc/mysql/conf.d/
# Copia los scripts de inicialización
COPY init.sql /docker-entrypoint-initdb.d/
